server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: servive-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tDaa9ZowFhq4SPu9bj7
    keySecret: DDO4IUMZpYfX8GoyWAxweN0Z8EcEif
    bucketName: ljj-srb-file